# Generated by Django 5.0.10 on 2026-02-25 15:30

from django.db import migrations, models


def set_display_order(apps, schema_editor):
    Video = apps.get_model("api", "Video")
    ordered_ids = list(
        Video.objects.order_by("created_at", "id").values_list("id", flat=True)
    )
    for idx, video_id in enumerate(ordered_ids, start=1):
        Video.objects.filter(pk=video_id).update(display_order=idx)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_upload_session_and_job_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(set_display_order, reverse_code=noop_reverse),
    ]
