volumes:
  pg_data:
  media:
  static:
  certbot_conf:
  certbot_www:

services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: ${DOCKER_USERNAME}/r0m43k_web_portal-backend:latest
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - media:/app/media
      - static:/app/staticfiles
    command: >
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 2
      --threads 4
      --worker-class gthread
      --timeout 300
      --access-logfile -
      --error-logfile -
      --log-level debug
      --capture-output
    restart: unless-stopped
  frontend:
    image: ${DOCKER_USERNAME}/r0m43k_web_portal-frontend:latest
    restart: unless-stopped

  gateway:
    image: ${DOCKER_USERNAME}/r0m43k_web_portal-gateway:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - media:/srv/media
      - static:/srv/static
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    profiles: ["certbot"]
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
