volumes:
  pg_data:
  media:
  static:

services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKER_USERNAME}/r0m43k_web_portal-backend:latest
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - media:/app/media
      - static:/app/staticfiles
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsu &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60"

  frontend: 
    image: ${DOCKER_USERNAME}/r0m43k_web_portal-frontend:latest
    restart: unless-stopped

  gateway:
    image: ${DOCKER_USERNAME}/r0m43k_web_portal-gateway:latest
    ports:
      - "80:80"
    volumes:
      - media:/srv/media:ro
      - static:/srv/static:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

