volumes:
  pg_data:
  media:
  static:
  certbot_webroot:

services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKER_USERNAME}/r0m43k_web_portal-backend:latest
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - media:/app/media
      - static:/app/staticfiles
    command: >
      gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 1 --timeout 60

  frontend: 
    image: ${DOCKER_USERNAME}/r0m43k_web_portal-frontend:latest
    restart: unless-stopped

  gateway:
    image: ${DOCKER_USERNAME}/r0m43k_web_portal-gateway:latest
    ports:
      - "80:80"
    volumes:
      - media:/srv/media:ro
      - static:/srv/static:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: >
      certonly --webroot
      --webroot-path=/var/www/certbot
      -d r0m43k.live -d www.r0m43k.live
      --email YOUR@email.com --agree-tos --no-eff-email

